name: DJGERBER
favicon: null
layout_spectrum: 0.80570522043854
typography_spectrum: 0.46352580143138766
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.056809924775734544
  lightness: 0.19045891286805272
  saturation: 0.01634653704240918
  rhythmicContrast: 0.6734579429030418
purpose: []
